#define __ZXNEXT 1

// Debug
#define DEBUG 1

#include <stdio.h>
#include <strings.h>
#include <arch/zxn.h>
#include <arch/zxn/esxdos.h>
#include <errno.h>
#include "lib/md5/md5.h"


// Missing 28mhz variable
#ifndef __RTM_28MHZ
    #define __RTM_28MHZ  0x03
#endif

// global variables
unsigned char fin  = 0xff;   // file descriptor
unsigned char fout = 0xff;   // file descriptor


// clean up at exit
static unsigned char old_cpu_speed;
void cleanup(void)
{
   if (fin != 0xff) esx_f_close(fin);
   if (fout != 0xff) esx_f_close(fout);
   
   puts("    ");

   ZXN_NEXTREGA(REG_TURBO_MODE, old_cpu_speed);
}

// CLI arguments
static char *cliOptions[] = {
    // Show help
    "-h",
    "--help",
    // filename
    "-f",
    // compare
    "-s",
    // Show progress
    "-p",
    // Output file
    "-o",
};

#define OP_H cliOptions[0]
#define OP_HELP cliOptions[1]
#define OP_F cliOptions[2]
#define OP_S cliOptions[3]
#define OP_P cliOptions[4]
#define OP_O cliOptions[5]

void usage(void) {
    puts("usage: .md5sum [-p | -s | -f | -h]");
}

/**
 * @brief help
 * 
 */
void help() {
  puts("md5sum - reformat input as morse code\n(produces the words by default)");
  puts("");
  usage();
  puts("");
  puts("DESCRIPTION");
  puts("");
  puts("-h, --help\n\tshow this help");
  puts("");
  puts("-s\n\tThe -s option for morse produces dots and dashes rather than words.");
  puts("");
  puts("-d\n\tDecode morse output consisting of dots and slashes (as generated by using the -s option).");
  puts("");
  puts("This is a port of OpenBSD morse.c to ZXNext");
}

/**
 * @brief 
 * 
 * @param str - The string
 * @param prefix - The prefix to match against
 * @return int 
 */
int startsWith(const char *str, const char *prefix) {
    // Compare the first strlen(prefix) characters of str with prefix
    return strncmp(str, prefix, strlen(prefix)) == 0;
}

// Print actual hash value
void print_hash(uint8_t *p){
    for(unsigned int i = 0; i < 16; ++i){
        printf("%02x", p[i]);
    }
    puts("");
}

int main(int argc, char *argv[]) {
    uint32_t len = 0;           // File length
    uint8_t result[16];         // MD5 result

    // Command line options
    unsigned char optsProgress = 0;     // Show progress
    unsigned char optsCompare = 0;      // Compare file and its md5
    unsigned char optsFile = 0;         // Use file for input
    unsigned char optsOutput = 0;       // To produce the ouptut file with the hash result
    char *optsFilename;                 // The filename to operate with
    char *optsOutputFilename;           // Output filename

    // Process command line options
    if (argc < 2) {
        usage();
        return 1;
    }

    for (unsigned char i = 1; i < argc; i++) {
        // Check for the help
        if (strcmp(argv[i], OP_H) == 0 || strcmp(argv[i], OP_HELP) == 0) {
            help();
            return 0;
        }

        if (strcmp(argv[i], OP_F) == 0) {
            optsFile = 1;
            // increase iterator, as the filename parameter
            // must be placed exactly after the `-f` option
            i++;
            // Save the reference
            optsFilename = argv[i];
        }

        // Compare existing file against its md5 checksum
        if (strcmp(argv[i], OP_S) == 0) {
            optsCompare = 1;
        }

        // To show progress
        if (strcmp(argv[i], OP_P) == 0) {
            optsProgress = 1;
        }

        // To generate output file
        if (strcmp(argv[i], OP_O) == 0) {
            optsOutput = 1;
            if (startsWith(argv[i + 1], "-") != 1) {
                i++;
                optsOutputFilename = argv[i];
            }
        }
    }


    #ifdef DEBUG
    printf("file: %d\n", optsFile);
    if (optsFile != 0) {
        printf("filename:|%s|\n", optsFilename);
    }
    printf("output: %d\n", optsOutput);
    if (optsOutputFilename != NULL) {
        printf("output filename:|%s|\n", optsOutputFilename);
    }
    printf("progress: %d\n", optsProgress);
    printf("compare: %d\n", optsCompare);
    #endif

    // Prepare
    old_cpu_speed = ZXN_READ_REG(REG_TURBO_MODE);
    ZXN_NEXTREG(REG_TURBO_MODE, __RTM_28MHZ);
    atexit(cleanup);

    if (optsFile == 0) {
        // We use input as a source
        #ifdef DEBUG
        printf("We use input as a source\n");
        #endif
        md5String("Hello next!", result);
    } else {
        // We use file as a source
        #ifdef DEBUG
        printf("We use file as a source\n");
        #endif
        // Try to open the file
        errno = 0;
        fin = esx_f_open(optsFilename, ESXDOS_MODE_R);
        if (errno != 0) {
            printf("Error opening file:  %s\n", optsFilename);
            // exit(1);
            return 1;
        }

        md5File(&fin, 0, result);
        
        // Close the file
        esx_f_close(fin);
    }

    if (optsOutput == 0) {
        // Result to the screen
        print_hash(result);
    } else {
        // Result to the file

    }
    
    // example:
    // /home/syr/work/zx-spectrum/z88dk/src/z80asm/t/1451/hexdump.c
    
    return 0;
}